name: "Build: Cleanup Residue"

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Swarm Loadbalancer"]
    types:
      - completed

jobs:
  cleanup-delete-candidate-image:
    name: Delete candidate image
    runs-on: ubuntu-latest
    steps:
      - run: docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
      - uses: dataaxiom/ghcr-cleanup-action@v1.0.3
        with:
          owner: benzine-framework
          repository: docker-swarm-loadbalancer
          name: bouncer
          tags: build-${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
  cleanup-untagged-images:
    name: Delete untagged images
    runs-on: ubuntu-latest
    steps:
      - run: docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
      - uses: dataaxiom/ghcr-cleanup-action@v1.0.3
        with:
          owner: benzine-framework
          repository: docker-swarm-loadbalancer
          name: bouncer
          token: ${{ secrets.GITHUB_TOKEN }}
