name: "Build: Release"

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:

env:
  CANDIDATE_IMAGE: ghcr.io/benzine-framework/bouncer:build-${{ github.sha }}
  RELEASE_IMAGE_GHCR: ghcr.io/benzine-framework/bouncer:latest
  RELEASE_IMAGE_DOCKER: benzine/bouncer:latest

jobs:
  release-ghcr:
    name: Release GHCR
    runs-on: ubuntu-latest
    steps:
      - run: docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ${{ env.CANDIDATE_IMAGE }}
      - run: docker tag ${{ env.CANDIDATE_IMAGE }} ${{ env.RELEASE_IMAGE_GHCR }}
      - run: docker push ${{ env.RELEASE_IMAGE_GHCR }}

  release-docker-hub:
    name: Release Docker Hub
    runs-on: ubuntu-latest
    steps:
      - run: docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker login docker.io -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker pull ${{ env.CANDIDATE_IMAGE }}
      - run: docker tag ${{ env.CANDIDATE_IMAGE }} ${{ env.RELEASE_IMAGE_DOCKER }}
      - run: docker push ${{ env.RELEASE_IMAGE_DOCKER }}
