name: "Build: Cleanup Residue"

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Swarm Loadbalancer"]
    types:
      - completed

env:
  CANDIDATE_IMAGE: ghcr.io/benzine-framework/bouncer
  CANDIDATE_TAG: build-${{ github.sha }}

jobs:
  cleanup-delete-candidate-image:
    name: Delete candidate image
    runs-on: ubuntu-latest
    steps:
      - run: docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
      - uses: dataaxiom/ghcr-cleanup-action@main
        with:
          owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          name: ${{ env.CANDIDATE_IMAGE }}
          tags: ${{ env.CANDIDATE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
  cleanup-untagged-images:
    name: Delete untagged images
    runs-on: ubuntu-latest
    steps:
      - run: docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
      - uses: dataaxiom/ghcr-cleanup-action@main
        with:
          owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          name: ${{ env.CANDIDATE_IMAGE }}
          token: ${{ secrets.GITHUB_TOKEN }}
