name: "Quality Control: Trunk Check"

permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:

jobs:
  trunk-check:
    name: Trunk Check Runner
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
    steps:
      - uses: benzine-framework/action-setup-php@main
      - name: "Trunk Check"
        uses: trunk-io/trunk-action@v1
